name: tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
        mysql:
            image: mysql:8.0
            env:
                MYSQL_ROOT_PASSWORD: password
                MYSQL_DATABASE: packages
            ports:
                - 3306:3306
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      -   name: Checkout code
          uses: actions/checkout@v4

      -   name: Install SQLite 3
          run: |
            sudo apt-get update
            sudo apt-get install sqlite3 -y

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.3
            extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
            coverage: none

      -   name: Install dependencies
          run: |
            composer install --no-scripts --no-interaction

      -   name: Execute tests
          run: vendor/bin/phpunit
